/* quantum.lisp is for wxMaxima's wxMathML pretty prints */
load("pretty-print.lisp")$
load("dependency")$

requires("bloch")$
requires("decoherent")$
requires("krauss")$
requires("qubit")$
requires("spin")$
requires("super-op")$

/* Taking the hermi adjoint */
/* fixme: does adjoint do the same thing?*/
dagger(x) := conjugate(transpose(x));

/* Global Facts is used to simplify most caculation results */
GlobalFacts : [];

/* vim: set ft=maxima ts=4 et: */
